name: Snyk Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  snyk:
    name: Run Snyk tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node (если нужен) 
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci         

      - name: Run Snyk test
        uses: snyk/actions@v3
        with:
          command: test     
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Monitor for new issues
        uses: snyk/actions@v3
        with:
          command: monitor  
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
